---
# Spring Configuration
spring:
  application:
    name: @project.name@

server:
  tomcat:
    basedir: ${application.home}
    max-threads: 1
    access-log-enabled: true
    access-log-pattern: "%t lbip=%h identd=%l user=%u status=%s method=%m url=%U bytes=%b duration=%D"

database:
  name: "root"
  host: "localhost"
  port: 8529
  user: "root"
  password: ""
  connectionTtl: 30000
  maxConnections: 50
  dataBaseName: demo_2
  vertexCollectionName: users_2
  edgeCollectionName: relations_2
  graphName: user_graph_2
